### ISSUE TITLE
Unable to connect to PPPoE Server from external device

### ISSUE THREAD

**Issue by odravison** [longwdl/docker-pppoe#1]
HI,
I'm facing an issue that seems more like a personal technical problem.

After running up the PPPoE Server in container, I'm able to connect using the `docker0` interface on my host machine. 

Following these steps: 
1. I run the PPPOECONF software on the host; 
2. All my host interfaces are scanned (including `docker0`);
3. When `docker0` is scanned the PPPoE Server is found and the connect flow goes just right;

I had try it from a external device, connected from my ethernet physical interface (enp5s0) but I cannot connect successfully with the PPPoE Server. 

I think that's is because my ethernet interface (enp5s0) don't know how to "pass to docker0" the PPPoE Connection Request. That's whats make sense to me, because when I run the container with `--network host` option, then works.

Do you know how to figured out this situation?

Thanks in advanced.

**Comment by longwdl** [comment]
Do you correctly install [dreamcat4/pipework](https://hub.docker.com/r/dreamcat4/pipework/)?

Or you can run PPPoE server on the host network, env PPPOE_IFACE should be a exist interface on your server (which you can connect from your ethernet physical interface enp5s0).

```
pppoe:
  build: .
  privileged: true
  net: host
  restart: always
  environment:
  - PPPOE_DNS1=119.29.29.29
  - PPPOE_DNS2=114.114.114.114
  - PPPOE_LOCAL=11.11.11.1
  - PPPOE_REMOTE=11.11.11.11
  - PPPOE_NUM=20
  - PPPOE_IFACE=eth1
```
